### ISSUE TITLE
lvr2_ros

### ISSUE THREAD

**Issue by nickvaras** [uos/lvr2#1]
Hi @spuetz, any plans for an lvr2_ros package and/or a refresh for organized_fast_mesh someday?

**Comment by twiemann** [comment]
For ROS integration you can have a look at our mesh_tools package which uses the new version: https://github.com/uos/mesh_tools

**Comment by twiemann** [comment]
Right now the organized fast mesh is not implemented i think

**Comment by nickvaras** [comment]
Thanks for the answer!
