### ISSUE TITLE
Rebloom 20.11.2 for Noetic  to depend on VTK7

### ISSUE THREAD

**Issue by mikaelarguedas** [uos/lvr2#11]
Currently the lv2r package is not installable in Noetic without conflicting with libpcl-dev.
The rosdep key has been fixed in https://github.com/ros/rosdistro/pull/27768, but the lvr2 deb has not been updated since making it still uninstallable on noetic.

Is it possible to rebloom/release v20.11.2 in Noetic to fix the dependency list ?

Thanks!

**Comment by spuetz** [comment]
@mikaelarguedas Thank you. We will work on that for the next release.

**Comment by mikaelarguedas** [comment]
Blooming/rereleasing the current version should take only ~5min and fix the problem.

What is the expected timeline for the next release?
