### ISSUE TITLE
Packages not part of Ubuntu standard repos

### ISSUE THREAD

**Issue by s-hemer** [uos/lvr2#5]
E: Für Paket »openmpi-dev« existiert kein Installationskandidat. 

There is libopenmpi-dev (https://packages.ubuntu.com/bionic/libopenmpi-dev).

E: Paket libvtk-qt-dev kann nicht gefunden werden.

There is libvtk7-qt-dev.

Please clarify/adopt the README. Additionally, surely cmake-ncurse-gui is no mandatory dependency, or?

**Comment by s-hemer** [comment]
... and this does not cover the incompatibility of vtk7 to the standard pcl1.8 packages at the mentioned 18.04/Bionic.

**Comment by mawiegand** [comment]
> E: Für Paket »openmpi-dev« existiert kein Installationskandidat.
> 
> There is libopenmpi-dev (https://packages.ubuntu.com/bionic/libopenmpi-dev).
> E: Paket libvtk-qt-dev kann nicht gefunden werden.
> 
> There is libvtk7-qt-dev.

You are right. It's allready fixed in the [master](https://github.com/uos/lvr2/tree/master) branch. See: f8b367d
 
> Additionally, surely cmake-ncurse-gui is no mandatory dependency, or?

No, it is not.

> ... and this does not cover the incompatibility of vtk7 to the standard pcl1.8 packages at the mentioned 18.04/Bionic.

LVR2 is also compatible with VTK6 but without `EDL shading` which is only available since VTK7.
So you could use the `libvtk6-qt-dev` package to satisfy the VTK dependency if youe require PCL.

I'll investigate it further since I am currently working on a Ubuntu package for LVR2.

**Comment by s-hemer** [comment]
> You are right. It's allready fixed in the master branch. See: f8b367d

Really did not have a look on that, sorry. Assumed that "develop" is ahead of "master" and also develop README says "18.04". May "master" should be default if it is ahead (and "develop" was merged anyway). From the pure name, one would assume that "develop" is ahead with new, unstable features and improvements, or?

> I'll investigate it further since I am currently working on an Ubuntu package for LVR2.

That sounds cool. Thanks for the insights

**Comment by mawiegand** [comment]
I created a first version of the Ubuntu packages with and without CUDA support.
The packages can be found and installed via our PPA: [Knowledge-Based Systems](https://launchpad.net/~kbs/+archive/ubuntu/kbs)
Feel free to test it and report any bugs here: [mawiegand/deb-lvr2](github.com/mawiegand/deb-lvr2)
